name: Tourism Project Pipeline - Windows

on:
  push:
    branches:
      - main   # Trigger on push to main branch
  workflow_dispatch:  # Manual trigger

jobs:

  # ---------------------------
  # Step 1: Register Dataset
  # ---------------------------
  register-dataset:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: pip install --upgrade pip
        shell: powershell

      - name: Install Project Requirements
        run: pip install -r MLOps/Tourism_Project/requirements.txt
        shell: powershell

      - name: Upload Dataset to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python MLOps/Tourism_Project/model_building/data_register.py
        shell: powershell

  # ---------------------------
  # Step 2: Data Preparation
  # ---------------------------
  data-prep:
    needs: register-dataset
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: pip install --upgrade pip
        shell: powershell

      - name: Install Project Requirements
        run: pip install -r MLOps/Tourism_Project/requirements.txt
        shell: powershell

      - name: Run Data Preparation
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python MLOps/Tourism_Project/model_building/prep.py
        shell: powershell

  # ---------------------------
  # Step 3: Model Training
  # ---------------------------
  model-training:
    needs: data-prep
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: pip install --upgrade pip
        shell: powershell

      - name: Install Project Requirements
        run: pip install -r MLOps/Tourism_Project/requirements.txt
        shell: powershell

      - name: Start MLflow Server
        run: Start-Process -NoNewWindow -FilePath "mlflow" -ArgumentList "ui --port 5000"
        shell: powershell

      - name: Model Building
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python MLOps/Tourism_Project/model_building/train.py
        shell: powershell

  # ---------------------------
  # Step 4: Deploy Hosting
  # ---------------------------
  deploy-hosting:
    needs: [model-training, data-prep, register-dataset]
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: pip install --upgrade pip
        shell: powershell

      - name: Install Project Requirements
        run: pip install -r MLOps/Tourism_Project/requirements.txt
        shell: powershell

      - name: Push Files to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python MLOps/Tourism_Project/hosting/hosting.py
        shell: powershell
